spring.application.name=gpi-tracker

# ===== SERVEUR =====
server.port=8081

# ===== ORACLE =====
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.fetch_size=50
# ===== KEYCLOAK RESOURCE SERVER =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/gpi-tracker-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/gpi-tracker-realm/protocol/openid-connect/certs

# ===== KEYCLOAK ADMIN =====
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin-gpi
keycloak.admin.password=Admin123!
keycloak.admin.target-realm=gpi-tracker-realm

# ===== EMAIL =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jemaichaima68@gmail.com
spring.mail.password=edteszugudvpkmcf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== APP =====
app.frontend.url=http://localhost:4200
app.name=GPI Tracker

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===== SWIFT / GPI =====
swift.received.path=C:/gpi-project/swift/client recu
swift.received.archive.path=C:/gpi-project/swift/client recu/archive
swift.emitted.path=C:/gpi-project/swift/client emis
swift.emitted.archive.path=C:/gpi-project/swift/client emis/archive
swift.watcher.delay=30000
spring.task.scheduling.pool.size=2